name: Generate UDP Playlist

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 时间 01:00（北京时间 09:00）自动运行
    workflow_dispatch:
    分支:
      - main
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run 江苏电信组播源.exe
        run: |
          cd udpxy
          江苏电信组播源.exe


      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add udplist.txt udplist.m3u
          git commit -m "Update UDP and M3U playlists"
          git push
