name: itvlist

on:
  schedule:
    - cron: '0 21,9 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-22.04@20240422.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        #run: pip install selenium==4.19.0 requests==2.31.0 futures==3.0.5 eventlet==0.36.1
        run: pip install selenium requests futures eventlet aiohttp aiofiles

      #- name: Run 江苏电信组播.exe
        #run: python ${{ github.workspace }}/江苏电信组播.exe

      - name: Add Custom Channels
        run: |
          cat szdf.txt >> itvlist.txt  # 追加多个直播源
        
           
      - name: 提交更改
        run: |
          git config --local user.email "gzj7003@163.com"
          git config --local user.name "gzj7003"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
